server {
    listen 80;
    # testing actions

    # adicionar certificado e trocar para "listen 443 ssl" quando o
    # backend/frontend estiverem prontos (requisito do subject: HTTPS/WSS).

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }
}
