on:
  pull_request:
  
jobs:
  move-card:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
    steps:
      - run: |
          gh project item-edit 3 \
            --owner robertodelfranco \
            --url ${{ github.event.pull_request.html_url }} \
            --field "Status" \
            --value "In Review"
